### ISSUE TITLE
steps.getxml.outputs.info structure

### ISSUE THREAD

**Issue by phonglt7** [mavrosxristoforos/get-xml-info#1]
Hi, could you please provide the structure of the ${{ steps.getxml.outputs.info }} object? How to access inner text, how to access attributes?

**Comment by mavrosxristoforos** [comment]
Hi there! The ${{ steps.getxml.outputs.info }} is just a string or an array of strings, which is either the inner text, or the attribute value, depending on your xpath.
Example:
```
<xml>
  <parent name="Joey">
       <children>
         <child>Chandler</child>
         <child>Phoebe</child>
       </children>
  </parent>
</xml>
```

xpath: '//parent/@name' will return 'Joey'
xpath: '//child' will return array[0 => 'Chandler', 1 => 'Phoebe']
