### ISSUE TITLE
The `set-output` command is deprecated and will be disabled soon.

### ISSUE THREAD

**Issue by bmos** [mavrosxristoforos/get-xml-info#14]
> The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

https://github.com/mavrosxristoforos/get-xml-info/blob/749cc7ecda18372226181a390717a4cab5439eb5/index.js#L49

https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-output-parameter

https://github.com/orgs/community/discussions/35994

**Comment by mavrosxristoforos** [comment]
Makes sense. However, does anyone know if the @actions/core package is going to update? We're not writing in stdout here, we're using the `core.setOutput` function...

**Comment by bmos** [comment]
Already has been.
Another heading explains this:
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/#patching-your-actions-and-workflows

> Action authors who are using the toolkit should update the @actions/core package to v1.10.0 or greater to get the updated saveState and setOutput 

Looks like perhaps I was mistaken in which action is causing the error as you're already on that version:
https://github.com/mavrosxristoforos/get-xml-info/blob/0f3de2c5e7fb49e9617b2db2f52e56e2e2ccb584/package.json#L13
