### ISSUE TITLE
License inconsistency

### ISSUE THREAD

**Issue by Teko012** [mavrosxristoforos/get-xml-info#17]
The `package.json` (and `package-lock.json`) files say the licensing is `ISC`, while the LICENSE in the repo says it is licensed under `GPL-3.0 license`. To match it, it should be `GPL-3.0-or-later` or something similar [per the documentation](https://docs.npmjs.com/cli/v9/configuring-npm/package-json#license) ([all the options](https://spdx.org/licenses/)), or the repo should be updated with the correct license.

**Comment by mavrosxristoforos** [comment]
Thank you for noticing. Can you please change it and create a PR?

**Comment by Teko012** [comment]
Sure
