### ISSUE TITLE
Feature Request: Need to a way to continue if no nodes are returned

### ISSUE THREAD

**Issue by michaely-ln** [mavrosxristoforos/get-xml-info#8]
I need to check if a value is present in an XML file.  If yes, use the value, it no, supply my own default.  This step causes an error and breaks the workflow in what is a normal event for my use case. 

Proposed solution: 
* throw a warning, not an error, if xpath is formed correctly but no nodes are found
* or, better yet, let me choose what happens on an empty result with a parameter, for example:
* * zero-nodes-action = error|warn|silent

**Comment by mavrosxristoforos** [comment]
That's an excellent suggestion. Would you like to make a pull request?

**Comment by michaely-ln** [comment]
I've never written a line of javascript, so I can't do it with efficiency.  If no one has time then I'll spend a few hours on a weekend and figure it out.  JS looks pretty straightforward.

**Comment by mavrosxristoforos** [comment]
Well… Looks can be very deceiving when it comes to Javascript. However, please do take a moment on the weekend if you want to, and if you can't, maybe I'll be able to do it next week.

**Comment by ismail44** [comment]
@mavrosxristoforos I've cloned the repo and created a branch to address this, however, it's not allowing me to push my branch to create a PR... can you allow?
